### ISSUE TITLE
Trouble running the example 

### ISSUE THREAD

**Issue by qu-tan-um** [debjyoti0891/quantum-chain#2]
I was trying the provided example by `python3 qchain.py ./tests/sample_ckt.real ./tests/qx15.gml`. This is the output:
```
Creating work directory: genfiles/
Creating benchmark directory: genfiles/sample_ckt/
Creating graph directory: genfiles/sample_ckt/topofiles/
Work directory set : None
Topology graph directory set : genfiles/sample_ckt/topofiles/
Loaded circuit ./tests/sample_ckt.real with 4 qubits
Base quantum computer configuration : ./tests/qx15.gml
Loading graph file: ./tests/qx15.gml
#vertices : 14 #edges : 18
Traceback (most recent call last):
  File "qchain.py", line 234, in <module>
    chain.mapNN(sys.argv[1],sys.argv[2],w)
  File "qchain.py", line 114, in mapNN
    topographs = self.__getTopographs(graphfile,qubitCount)
  File "qchain.py", line 40, in __getTopographs
    topoGen.genTopoGraph(n,k,tries)
  File "/curr/bctan/quantum-chain/graphtools/topoGraphGen.py", line 45, in genTopoGraph
    for e in self.__graph.es.select(_source=v):
  File "/home/bctan/anaconda3/lib/python3.7/site-packages/igraph/__init__.py", line 4054, in select
    candidates.update(es.graph.incident(v))
igraph._igraph.InternalError: Error at /project/vendor/source/igraph/src/type_indexededgelist.c:1671: cannot get neighbors, Invalid vertex id
```
My computer has `Ubutun 16.04.6 LTS (Xenial Xerus)`, `python-igraph 0.8.2`,  and `Gurobi Optimizer version 9.0.0 build v9.0.0rc2 (linux64)`.

**Comment by debjyoti0891** [comment]
We have fixed the issue. Let us know if you need any further help.
